### ISSUE TITLE
plc-applicator support multibase

### ISSUE THREAD

**Issue by ledlamp** [mary-ext/boat#1]
![2024-12-01_21-14-03 089_Apply_PLC_operations_—_boat_-_Vivaldi](https://github.com/user-attachments/assets/2d927488-70c3-4cad-b22a-ea599736a191)

the key I have is multibase now I have to figure out how to convert it

**Comment by mary-ext** [comment]
huh, how did you get multibase private keys to begin with?

**Comment by ledlamp** [comment]
goat crypto generate

**Comment by mary-ext** [comment]
Multikey-based private keys (the same ones that `goat` generates) are now supported.
https://github.com/mary-ext/boat/commit/67c65f7009527a8df786d9ae25429c8af7ae08d9
